### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by clamp131** [mehrdadbakhtiari/adVNTR#15]
I tried to add my own model using this:

advntr addmodel -r /rd/tansj/vntr/vntr_data/dm6.fa -c chr2L -p GTTGTCTTTTTGGTGGTTGGTTCTTCTGTTGTCTTATGGGTTGTTGTCTTACGAGTGGTTGGCTCCTGAGTTGTCCTTTCAGTTGTTTCCCTCTTTGTAGTTGGCTCTCTAGTAGTCTTTGTGGTTGATGTTTTGCGAGTAGTTGGTTCTTCGGTAGGCTTTAAAGTAGTTGATTTCTTAGTTGTGGGTTCATGAGTGC -s 9898540 -e 9902555

it is a VNTR in fruitfly genome. But I got some errors:

Traceback (most recent call last):
  File "/home/tansj/program/miniconda2/bin/advntr", line 6, in <module>
    sys.exit(advntr.__main__.main())
  File "/home/tansj/program/miniconda2/lib/python2.7/site-packages/advntr/__main__.py", line 118, in main
    add_model(args, addmodel_parser)
  File "/home/tansj/program/miniconda2/lib/python2.7/site-packages/advntr/advntr_commands.py", line 141, in add_model
    vntr_id = get_largest_id_in_database() + 1
  File "/home/tansj/program/miniconda2/lib/python2.7/site-packages/advntr/models.py", line 178, in get_largest_id_in_database
    db = sqlite3.connect(settings.TRAINED_MODELS_DB)
sqlite3.OperationalError: unable to open database file

I did not use sqlite3 before. We have mysql. Is there something I need to do before running advntr?

**Comment by mehrdadbakhtiari** [comment]
Dear @clamp131,

Sorry for my delayed response. You don't need mysql to run the tool (sqlite is automatically installed from the requirements)

This command assumes there is a database file and tries to add your model to it, can you download [vntr_data.zip](https://cseweb.ucsd.edu/~mbakhtia/adVNTR/vntr_data.zip) and then run that command to add the VNTR?

I will modify the code so it will create everything if this file is not downloaded, but for now you can download it although you don't use its VNTRs.

Thanks for reporting the problem

**Comment by mehrdadbakhtiari** [comment]
Dear @clamp131,

Thank you again for reporting the problem. This issue is fixed now. So, you don't need to download vntr_data if you just run the tool on your own models.

Also, please consider the following:
* Since your VNTR is too large, accurate genotyping is not possible. Please use `--expansion` and specify the coverage with `-c` parameter to get the estimate.
* You can use `--haploid` if you are running adVNTR for fruitfly (By default, adVNTR assumes the genome is diploid)

Let me know if you face with any other issue.
