### ISSUE TITLE
Support for python-3.7

### ISSUE THREAD

**Issue by mehrdadbakhtiari** [mehrdadbakhtiari/adVNTR#28]
All required packages have released an update to support python-3.7, so we can support it as well.

**Comment by nbargues** [comment]
Hi, I have an error due to python version when installing by conda. Any idea how to pass this error ?
Error:

(gene) cxx5wc@gesvr004x:~$ conda install -c bioconda advntr
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.                                                                                                                                             failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - advntr -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by mehrdadbakhtiari** [comment]
Hi Nicolas,
Unfortunately the requirement chain is still not updated and advntr is not available for python 3.7. Can you create your virtual environment with python 3.6 and try installing advntr on that?
It can be done with `conda create -n test_env python=3.6`

Thanks,
Mehrdad

**Comment by nbargues** [comment]
Yes I just create a new env with python 3.6 and the install works. Thanks. To bad for the compatibility.
