### ISSUE TITLE
outformat

### ISSUE THREAD

**Issue by psychrb** [mehrdadbakhtiari/adVNTR#36]
For an adVNTR output in "vcf format:, is the command just --outfmt vcf
I am getting bed and text to output, but not vcf...Not clear. If you can advise...Thanks.
advntr genotype -m vntr_data/hg19_selected_VNTRs_Illumina.db -f BAM --working_directory ./ -of text -o NAME

**Comment by Jong-hun-Park** [comment]
Hi,

adVNTR supports VCF output since the version of 1.4.0. Can you first check if you used the right version? You can check the version from the output file or code (advntr/__init__.py).

The parameter --outfmt is the right way to specify the output format. It would be also helpful if you can let us know the exact command you used as I don't see the --outfmt parameter in the last line.

**Comment by psychrb** [comment]
The previous command had -of text parameter. Will check version.

**Comment by psychrb** [comment]
Yes, this did output a vcf file and version was the issue. The vcf seems transposed with rows instead of columns...Is that as per design...See below as header of vcf 

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	
chr1	
700243	
.	
CGAGGCGGGAAGATCACTTGATATCAGGAGTCGAGGCGGGAAGATCACTTGACGTCAGGAGTT	
.	
.	
.	
END=700306;VID=156;RU=CGAGGCGGGAAGATCACTTGACATCAGGAGTT;RC=2	
GT:DP:SR:FR:ML	
0/0:34:13:21:1.0000
chr1	
777293	
.	
AGAAATGCTTCTTTAGAAATGCTTCTTT	
.	
.	
.	
END=777321;VID=174;RU=AGAAATGCTTCTTT;RC=2	
GT:DP:SR:FR:ML	
0/0:37:20:17:1.0000

**Comment by psychrb** [comment]
Am I supposed to manually transpose the vcfoutput...? Or is this intended as adVNTR vcf output? Thanks.

**Comment by psychrb** [comment]
Am I supposed to manually transpose the vcf output...? Or is this intended as adVNTR vcf output? Thanks.

**Comment by Jong-hun-Park** [comment]
Hi,

Thanks for checking the version. 
That's absolutely not intended behavior, and it is an issue caused by python version (That works with Python2). We will fix the issue very soon, but to use the fixed version, you will need to update the adVNTR using the latest code. How did you install adVNTR? through conda or github?

**Comment by psychrb** [comment]
Used Python 3. Not OK with Python 3??

**Comment by psychrb** [comment]
Used Python 3 and current adVNTR version hosted on GitHub,

**Comment by psychrb** [comment]
Used Python 3 and current adVNTR version hosted on GitHub...Should Python 3 not be used then??

**Comment by psychrb** [comment]
Used Python 3 and current adVNTR version hosted on GitHub...Should Python 3 not be used then??

**Comment by psychrb** [comment]
I now see: 'Fix vcf output for both python2 and python3'. Should I re-load and run adVNTR again? With which Python version.

**Comment by Jong-hun-Park** [comment]
Yes, you need to re-load the code and re-install adVNTR again from Github. Sorry for the inconvenience. 
As of now, either Python 2 or 3 should work fine.
